/**
 * Pack the whole app into a single AI-editable Markdown file.
 *
 * Walks an explicit allowlist of project directories, skips noise
 * (node_modules, build output, lockfiles, source maps, binary assets, secrets,
 * and internal/agent folders) and concatenates every relevant source/config
 * file into ONE Markdown document with an orientation header, a directory tree,
 * and one fenced code block per file.
 *
 * Run with: pnpm --filter @workspace/scripts run pack-app
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));

const OUTPUT_REL = "exports/trading-copilot-app-bundle.md";

// Roots to include, relative to the repo root. May be files or directories.
const INCLUDE_ROOTS = [
  "package.json",
  "pnpm-workspace.yaml",
  "tsconfig.base.json",
  "tsconfig.json",
  "replit.md",
  "artifacts/trading-copilot",
  "artifacts/api-server",
  "lib/api-spec",
  "lib/api-zod",
  "lib/api-client-react",
  "lib/db",
];

// Directory names that are always skipped during recursion.
const EXCLUDE_DIR_NAMES = new Set([
  "node_modules",
  "dist",
  "build",
  "coverage",
  ".git",
  ".turbo",
  ".cache",
  ".next",
  ".vite",
  ".local",
  ".agents",
  ".replit-artifact",
]);

// File extensions that are binary / generated noise and never embedded as text.
const EXCLUDE_EXTS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".webp",
  ".ico",
  ".bmp",
  ".tif",
  ".tiff",
  ".avif",
  ".woff",
  ".woff2",
  ".ttf",
  ".otf",
  ".eot",
  ".mp4",
  ".webm",
  ".mov",
  ".mp3",
  ".wav",
  ".ogg",
  ".pdf",
  ".zip",
  ".gz",
  ".tgz",
  ".7z",
  ".rar",
  ".map",
  ".tsbuildinfo",
]);

const MAX_FILE_BYTES = 512 * 1024;

async function findRepoRoot(start: string): Promise<string> {
  let dir = start;
  for (let i = 0; i < 12; i++) {
    try {
      await fs.access(path.join(dir, "pnpm-workspace.yaml"));
      return dir;
    } catch {
      // keep walking up
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error("Could not locate repo root (pnpm-workspace.yaml not found)");
}

function isSecretFile(name: string): boolean {
  if (name === ".env") return true;
  if (name.startsWith(".env.")) {
    return !/\.(example|sample|template)$/i.test(name);
  }
  return /\.(pem|key|p12|pfx|keystore|crt|cer)$/i.test(name);
}

async function walk(repoRoot: string, dir: string, out: string[]): Promise<void> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (EXCLUDE_DIR_NAMES.has(entry.name)) continue;
      if (entry.name.startsWith(".")) continue;
      await walk(repoRoot, abs, out);
    } else if (entry.isFile()) {
      const lower = entry.name.toLowerCase();
      const ext = path.extname(lower);
      // Dotfiles like ".tsbuildinfo" report an empty extname, so also match by suffix.
      if (EXCLUDE_EXTS.has(ext)) continue;
      if ([...EXCLUDE_EXTS].some((e) => lower.endsWith(e))) continue;
      if (isSecretFile(entry.name)) continue;
      out.push(path.relative(repoRoot, abs).split(path.sep).join("/"));
    }
  }
}

async function collectFiles(repoRoot: string): Promise<string[]> {
  const out: string[] = [];
  for (const rel of INCLUDE_ROOTS) {
    const abs = path.join(repoRoot, rel);
    let st;
    try {
      st = await fs.stat(abs);
    } catch {
      continue;
    }
    if (st.isFile()) {
      out.push(rel);
    } else if (st.isDirectory()) {
      await walk(repoRoot, abs, out);
    }
  }
  return [...new Set(out)].sort();
}

function langFor(file: string): string {
  const ext = path.extname(file).toLowerCase();
  switch (ext) {
    case ".ts":
    case ".mts":
    case ".cts":
      return "ts";
    case ".tsx":
      return "tsx";
    case ".js":
    case ".mjs":
    case ".cjs":
      return "js";
    case ".jsx":
      return "jsx";
    case ".json":
      return "json";
    case ".css":
      return "css";
    case ".html":
      return "html";
    case ".yaml":
    case ".yml":
      return "yaml";
    case ".md":
      return "markdown";
    case ".toml":
      return "toml";
    case ".sql":
      return "sql";
    case ".sh":
      return "bash";
    case ".svg":
      return "xml";
    default:
      return "";
  }
}

function fenceFor(content: string): string {
  const runs = content.match(/`+/g) ?? [];
  let max = 0;
  for (const run of runs) max = Math.max(max, run.length);
  return "`".repeat(Math.max(3, max + 1));
}

function looksGenerated(content: string): boolean {
  const head = content.slice(0, 2000);
  return /generated by orval|auto-?generated|do not edit/i.test(head);
}

function renderTree(files: string[]): string {
  interface Node {
    children: Map<string, Node>;
  }
  const root: Node = { children: new Map() };
  for (const file of files) {
    const parts = file.split("/");
    let cur = root;
    for (const part of parts) {
      let next = cur.children.get(part);
      if (!next) {
        next = { children: new Map() };
        cur.children.set(part, next);
      }
      cur = next;
    }
  }
  const lines: string[] = ["."];
  const rec = (node: Node, prefix: string): void => {
    const entries = [...node.children.entries()].sort((a, b) => {
      const aDir = a[1].children.size > 0;
      const bDir = b[1].children.size > 0;
      if (aDir !== bDir) return aDir ? -1 : 1;
      return a[0].localeCompare(b[0]);
    });
    entries.forEach(([name, child], idx) => {
      const last = idx === entries.length - 1;
      const isDir = child.children.size > 0;
      lines.push(`${prefix}${last ? "└── " : "├── "}${name}${isDir ? "/" : ""}`);
      rec(child, prefix + (last ? "    " : "│   "));
    });
  };
  rec(root, "");
  return lines.join("\n");
}

function buildHeader(fileCount: number, tree: string): string {
  return `# Ace Trades Trading Copilot — Full Source Bundle

> **This single file contains the complete source code of the app.** It is a
> packed export meant to be pasted or uploaded into another AI coding tool
> (Claude, Gemini, dyad, GitHub-based assistants, online sandboxes, etc.) so the
> AI can read and edit the real code without access to the original project.

## How to read this file (instructions for an AI)

- This document is the entire project, concatenated. It contains **${fileCount}
  files**.
- The **Directory tree** section below shows the layout. The **Files** section
  contains every file's full contents.
- Each file is delimited by a heading of the form \`### \\\`relative/path\\\`\`
  followed by a fenced code block with the file's contents and a language hint.
- The fence length varies per file (it is always longer than any run of
  backticks inside that file), so a Markdown file's own \`\`\`\`\`\`\`\`\`\` fences will be
  wrapped in a longer fence. Match the opening and closing fence lengths.
- To propose an edit, identify the file by its \`relative/path\` heading and
  return the changed file (or a unified diff against it). Preserve the existing
  paths and project structure unless a change explicitly requires moving files.

## What this app is

Ace Trades is a beginner-friendly trading copilot that works for any instrument
and market — futures, stocks, forex, and crypto (Nasdaq-100 / NQ futures is the
default). Users can: upload a chart screenshot for a graded setup analysis, keep
a personal trading plan with a risk calculator that sizes positions (contracts/
shares/lots) or shows plain dollar risk, paste a news headline/event to get a
predicted market impact, get a longer "trader review" of a chart, see session
timing guidance, debrief a completed trade, and review a journal of past analyses
with stats. Instruments come from built-in presets or a fully custom definition.
Every AI feature explains itself in plain English for new traders and adapts to
the selected market.

## Tech stack

- **Monorepo:** pnpm workspaces, Node.js 24, TypeScript 5.9.
- **Web app:** React 19 + Vite 7 (\`artifacts/trading-copilot\`), Tailwind CSS,
  wouter (routing), TanStack Query (data fetching).
- **API server:** Express 5 (\`artifacts/api-server\`) — holds the Anthropic
  credentials and performs all AI calls; also handles Stripe and health checks.
- **Database:** PostgreSQL + Drizzle ORM (\`lib/db\`).
- **Validation & contract:** Zod, with an OpenAPI-first contract
  (\`lib/api-spec/openapi.yaml\`). Orval generates the Zod schemas (\`lib/api-zod\`)
  and React Query hooks (\`lib/api-client-react\`) from that spec.

## Architecture (important)

- **The frontend never calls the AI directly.** All AI analysis goes through the
  API server, which holds the Anthropic API key. Doing AI calls in the browser
  would leak the key.
- **Contract-first:** the API is defined in \`lib/api-spec/openapi.yaml\`. The
  React Query hooks and Zod schemas are generated from it — to add or change an
  endpoint, edit the spec and re-run codegen rather than hand-writing client
  code. Files under \`lib/api-zod\` and \`lib/api-client-react\` marked
  *(generated)* are produced this way and should not be edited by hand.
- **User settings and the journal live only in the browser** (localStorage), not
  on a server.

## How to run it

From the repo root (after \`pnpm install\`):

- \`pnpm --filter @workspace/api-server run dev\` — run the API server.
- \`pnpm --filter @workspace/trading-copilot run dev\` — run the web app.
- \`pnpm run typecheck\` — full typecheck across all packages.
- \`pnpm run build\` — typecheck + build all packages.
- \`pnpm --filter @workspace/api-spec run codegen\` — regenerate API hooks and
  Zod schemas from the OpenAPI spec.
- \`pnpm --filter @workspace/db run push\` — push DB schema changes (dev only).

### Required environment variables (set these — values are NOT included here)

- \`DATABASE_URL\` — Postgres connection string.
- \`ANTHROPIC_API_KEY\` — used by the API server for all AI analysis.
- \`SESSION_SECRET\` — server session signing secret.
- \`STRIPE_LIVE_API_KEY\` — Stripe secret key (billing). Optional for local dev.

> Secrets are intentionally excluded from this bundle. Provide your own values
> via environment variables / a \`.env\` file.

## Regenerating this bundle

This file is a generated export of the app source; the packer that produces it
(\`scripts/src/pack-app.ts\`) lives in the original project and is intentionally
not part of this export. To refresh the bundle there, run
\`pnpm --filter @workspace/scripts run pack-app\`.

## Directory tree

\`\`\`text
${tree}
\`\`\`

## Files
`;
}

async function main(): Promise<void> {
  const repoRoot = await findRepoRoot(SCRIPT_DIR);
  const files = await collectFiles(repoRoot);

  if (files.some((f) => f.includes("node_modules/"))) {
    throw new Error("Refusing to write bundle: node_modules path leaked into file list");
  }

  const tree = renderTree(files);
  const parts: string[] = [buildHeader(files.length, tree)];

  let totalBytes = 0;
  let included = 0;
  let skippedBinary = 0;
  let skippedLarge = 0;

  for (const rel of files) {
    const abs = path.join(repoRoot, rel);
    const buf = await fs.readFile(abs);
    if (buf.includes(0)) {
      skippedBinary++;
      continue;
    }
    if (buf.byteLength > MAX_FILE_BYTES) {
      skippedLarge++;
      parts.push(
        `\n### \`${rel}\`\n\n> _Omitted from this bundle: file is ${(
          buf.byteLength / 1024
        ).toFixed(0)} KB, larger than the ${(MAX_FILE_BYTES / 1024).toFixed(
          0,
        )} KB per-file limit._\n`,
      );
      continue;
    }
    const content = buf.toString("utf8");
    const fence = fenceFor(content);
    const lang = langFor(rel);
    const generatedNote = looksGenerated(content)
      ? " *(generated — produced by codegen from `lib/api-spec/openapi.yaml`; do not edit by hand)*"
      : "";
    const body = content.endsWith("\n") ? content : content + "\n";
    parts.push(
      `\n### \`${rel}\`${generatedNote}\n\n${fence}${lang}\n${body}${fence}\n`,
    );
    totalBytes += buf.byteLength;
    included++;
  }

  const outAbs = path.join(repoRoot, OUTPUT_REL);
  await fs.mkdir(path.dirname(outAbs), { recursive: true });
  const output = parts.join("");
  await fs.writeFile(outAbs, output, "utf8");

  console.log(`Packed app bundle written to ${OUTPUT_REL}`);
  console.log(`  files included:  ${included}`);
  if (skippedBinary) console.log(`  skipped (binary): ${skippedBinary}`);
  if (skippedLarge) console.log(`  skipped (>limit): ${skippedLarge}`);
  console.log(`  source bytes:    ${(totalBytes / 1024).toFixed(0)} KB`);
  console.log(`  bundle size:     ${(output.length / 1024).toFixed(0)} KB`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
